mongo:  
  image: mongo:latest 
  ports:  
   - "27017:27017"  
  volumes:  
   - './data:/data/db'  
app:  
  build: .  
  command: bash -c "npm install; node index.js"  
  ports:  
   - "3000:3000"  
   - "5858:5858"  
  volumes:  
   - ./app:/usr/src/app  
  links:  
   - mongo  